# Generated by Django 4.2.7 on 2025-08-20 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("weather_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeasonalSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("winter", "Winter (Dec, Jan, Feb)"),
                            ("spring", "Spring (Mar, Apr, May)"),
                            ("summer", "Summer (Jun, Jul, Aug)"),
                            ("autumn", "Autumn (Sep, Oct, Nov)"),
                            ("annual", "Annual (All 12 months)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasonal_summaries",
                        to="weather_data.weatherparameter",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasonal_summaries",
                        to="weather_data.region",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seasonal Summary",
                "verbose_name_plural": "Seasonal Summaries",
                "ordering": ["-year", "season", "region", "parameter"],
                "indexes": [
                    models.Index(
                        fields=["year", "season"], name="weather_dat_year_75d792_idx"
                    ),
                    models.Index(
                        fields=["region", "parameter", "year"],
                        name="weather_dat_region__009e10_idx",
                    ),
                ],
                "unique_together": {("region", "parameter", "year", "season")},
            },
        ),
    ]
